.TH STS 1 "0.1alpha" Linux "User Manuals"
.SH NAME
.PP
sts \- simple terminal scroller
.SH SYNOPSIS
.PP
\fB\fCsts\fR [\fB\fC\-u\fR] [\fB\fC\-l\fR \fIbuf_limit\fP]
.SH DESCRIPTION
.PP
\fB\fCsts\fR is a pseudo terminal scroller for the simple terminal 
.BR st (1).
.SH OPTIONS
.TP
\fB\fC\-h\fR, \fB\fC\-\-help\fR
Show the terse help screen and exit.
.TP
\fB\fC\-u\fR, \fB\fC\-\-unlimited\fR
Enable unlimited backlog lines (\fB\fCdefault\fR). (same as \fB\fC\-l 0\fR)
.TP
\fB\fC\-l\fR \fIbuf_limit\fP, \fB\fC\-\-limit\fR \fIbuf_limit\fP
Specify the number of lines \fIbeyond the screen\fP \fB\fCsts\fR should remember for scrolling. Default is 0, meaning there is no limit. (see \fB\fC\-u\fR)
.TP
\fB\fC\-v\fR, \fB\fC\-\-version\fR
Show the version information and exit.
.SH BUGS
.PP
Bugs, issues, and feature requests should be sent to the issue tracker on Github: 
\[la]https://github.com/jeaye/sts/issues\[ra]\&.
.SH AUTHOR
.PP
Jeaye 
\[la]contact@jeaye.com\[ra]
.SH LICENSE
.PP
\fB\fCsts\fR is under the MIT license. See the \fILICENSE\fP file.
